# Generated by Django 3.2.25 on 2024-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_movie_movie1'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie1',
            name='images',
            field=models.ImageField(default='hhh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
